/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthenticateUserByName
 */
export interface AuthenticateUserByName {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateUserByName
     */
    username?: any;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateUserByName
     */
    password?: any;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateUserByName
     */
    pw?: any;
}
