/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BaseItemPerson
 */
export interface BaseItemPerson {
    /**
     * 
     * @type {string}
     * @memberof BaseItemPerson
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof BaseItemPerson
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof BaseItemPerson
     */
    role?: any;
    /**
     * 
     * @type {string}
     * @memberof BaseItemPerson
     */
    type?: BaseItemPersonTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BaseItemPerson
     */
    primaryImageTag?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum BaseItemPersonTypeEnum {
    Actor = 'Actor',
    Director = 'Director',
    Writer = 'Writer',
    Producer = 'Producer',
    GuestStar = 'GuestStar',
    Composer = 'Composer',
    Conductor = 'Conductor',
    Lyricist = 'Lyricist'
}

