/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConfigurationImageOption
 */
export interface ConfigurationImageOption {
    /**
     * 
     * @type {string}
     * @memberof ConfigurationImageOption
     */
    type?: ConfigurationImageOptionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ConfigurationImageOption
     */
    limit?: any;
    /**
     * 
     * @type {number}
     * @memberof ConfigurationImageOption
     */
    minWidth?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum ConfigurationImageOptionTypeEnum {
    Primary = 'Primary',
    Art = 'Art',
    Backdrop = 'Backdrop',
    Banner = 'Banner',
    Logo = 'Logo',
    Thumb = 'Thumb',
    Disc = 'Disc',
    Box = 'Box',
    Screenshot = 'Screenshot',
    Menu = 'Menu',
    Chapter = 'Chapter',
    BoxRear = 'BoxRear',
    Thumbnail = 'Thumbnail'
}

