/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConfigurationTypeOptions
 */
export interface ConfigurationTypeOptions {
    /**
     * 
     * @type {string}
     * @memberof ConfigurationTypeOptions
     */
    type?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ConfigurationTypeOptions
     */
    metadataFetchers?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ConfigurationTypeOptions
     */
    metadataFetcherOrder?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ConfigurationTypeOptions
     */
    imageFetchers?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ConfigurationTypeOptions
     */
    imageFetcherOrder?: any;
    /**
     * 
     * @type {Array&lt;ConfigurationImageOption&gt;}
     * @memberof ConfigurationTypeOptions
     */
    imageOptions?: any;
}
