/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DevicesLocalFileInfo
 */
export interface DevicesLocalFileInfo {
    /**
     * 
     * @type {string}
     * @memberof DevicesLocalFileInfo
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof DevicesLocalFileInfo
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof DevicesLocalFileInfo
     */
    album?: any;
    /**
     * 
     * @type {string}
     * @memberof DevicesLocalFileInfo
     */
    mimeType?: any;
}
