/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EmbyWebGenericEditEditorsEditorRoot
 */
export interface EmbyWebGenericEditEditorsEditorRoot {
    /**
     * 
     * @type {Array&lt;EmbyWebGenericEditConditionsPropertyCondition&gt;}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    propertyConditions?: any;
    /**
     * 
     * @type {Array&lt;EmbyWebGenericEditActionsPostbackAction&gt;}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    postbackActions?: any;
    /**
     * 
     * @type {EmbyWebGenericEditEditorsEditorButtonItem}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    titleButton?: any;
    /**
     * 
     * @type {Array&lt;EmbyWebGenericEditEditorsEditorBase&gt;}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    editorItems?: any;
    /**
     * 
     * @type {string}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    editorType?: EmbyWebGenericEditEditorsEditorRootEditorTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    allowEmpty?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    isReadOnly?: any;
    /**
     * 
     * @type {string}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    displayName?: any;
    /**
     * 
     * @type {string}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof EmbyWebGenericEditEditorsEditorRoot
     */
    parentId?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum EmbyWebGenericEditEditorsEditorRootEditorTypeEnum {
    Group = 'Group',
    Text = 'Text',
    Numeric = 'Numeric',
    Boolean = 'Boolean',
    SelectSingle = 'SelectSingle',
    SelectMultiple = 'SelectMultiple',
    Date = 'Date',
    FilePath = 'FilePath',
    FolderPath = 'FolderPath',
    StatusItem = 'StatusItem',
    ProgressItem = 'ProgressItem',
    ButtonItem = 'ButtonItem',
    ButtonGroup = 'ButtonGroup',
    CaptionItem = 'CaptionItem',
    LabelItem = 'LabelItem',
    ItemList = 'ItemList',
    RadioGroup = 'RadioGroup',
    DataGrid = 'DataGrid',
    PivotGrid = 'PivotGrid',
    SpacerItem = 'SpacerItem'
}

