/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EmbyReportsApiModelReportHeader
 */
export interface EmbyReportsApiModelReportHeader {
    /**
     * 
     * @type {string}
     * @memberof EmbyReportsApiModelReportHeader
     */
    headerFieldType?: EmbyReportsApiModelReportHeaderHeaderFieldTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EmbyReportsApiModelReportHeader
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof EmbyReportsApiModelReportHeader
     */
    fieldName?: EmbyReportsApiModelReportHeaderFieldNameEnum;
    /**
     * 
     * @type {string}
     * @memberof EmbyReportsApiModelReportHeader
     */
    sortField?: any;
    /**
     * 
     * @type {string}
     * @memberof EmbyReportsApiModelReportHeader
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof EmbyReportsApiModelReportHeader
     */
    itemViewType?: EmbyReportsApiModelReportHeaderItemViewTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof EmbyReportsApiModelReportHeader
     */
    visible?: any;
    /**
     * 
     * @type {string}
     * @memberof EmbyReportsApiModelReportHeader
     */
    displayType?: EmbyReportsApiModelReportHeaderDisplayTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof EmbyReportsApiModelReportHeader
     */
    showHeaderLabel?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EmbyReportsApiModelReportHeader
     */
    canGroup?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum EmbyReportsApiModelReportHeaderHeaderFieldTypeEnum {
    String = 'String',
    Boolean = 'Boolean',
    Date = 'Date',
    Time = 'Time',
    DateTime = 'DateTime',
    Int = 'Int',
    Image = 'Image',
    Object = 'Object',
    Minutes = 'Minutes'
}
/**
    * @export
    * @enum {string}
    */
export enum EmbyReportsApiModelReportHeaderFieldNameEnum {
    None = 'None',
    Path = 'Path',
    Name = 'Name',
    PremiereDate = 'PremiereDate',
    DateAdded = 'DateAdded',
    ReleaseDate = 'ReleaseDate',
    Runtime = 'Runtime',
    PlayCount = 'PlayCount',
    Season = 'Season',
    SeasonNumber = 'SeasonNumber',
    Series = 'Series',
    Network = 'Network',
    Year = 'Year',
    ParentalRating = 'ParentalRating',
    CommunityRating = 'CommunityRating',
    Trailers = 'Trailers',
    Specials = 'Specials',
    GameSystem = 'GameSystem',
    AlbumArtist = 'AlbumArtist',
    Album = 'Album',
    Disc = 'Disc',
    Track = 'Track',
    Audio = 'Audio',
    EmbeddedImage = 'EmbeddedImage',
    Video = 'Video',
    Resolution = 'Resolution',
    Subtitles = 'Subtitles',
    Genres = 'Genres',
    Countries = 'Countries',
    Status = 'Status',
    Tracks = 'Tracks',
    EpisodeSeries = 'EpisodeSeries',
    EpisodeSeason = 'EpisodeSeason',
    EpisodeNumber = 'EpisodeNumber',
    AudioAlbumArtist = 'AudioAlbumArtist',
    MusicArtist = 'MusicArtist',
    AudioAlbum = 'AudioAlbum',
    Locked = 'Locked',
    ImagePrimary = 'ImagePrimary',
    ImageBackdrop = 'ImageBackdrop',
    ImageLogo = 'ImageLogo',
    Actor = 'Actor',
    Studios = 'Studios',
    Composer = 'Composer',
    Director = 'Director',
    GuestStar = 'GuestStar',
    Producer = 'Producer',
    Writer = 'Writer',
    Artist = 'Artist',
    Years = 'Years',
    ParentalRatings = 'ParentalRatings',
    CommunityRatings = 'CommunityRatings',
    Overview = 'Overview',
    ShortOverview = 'ShortOverview',
    Type = 'Type',
    Date = 'Date',
    UserPrimaryImage = 'UserPrimaryImage',
    Severity = 'Severity',
    Item = 'Item',
    User = 'User',
    UserId = 'UserId'
}
/**
    * @export
    * @enum {string}
    */
export enum EmbyReportsApiModelReportHeaderItemViewTypeEnum {
    None = 'None',
    Detail = 'Detail',
    Edit = 'Edit',
    List = 'List',
    ItemByNameDetails = 'ItemByNameDetails',
    StatusImage = 'StatusImage',
    EmbeddedImage = 'EmbeddedImage',
    SubtitleImage = 'SubtitleImage',
    TrailersImage = 'TrailersImage',
    SpecialsImage = 'SpecialsImage',
    LockDataImage = 'LockDataImage',
    TagsPrimaryImage = 'TagsPrimaryImage',
    TagsBackdropImage = 'TagsBackdropImage',
    TagsLogoImage = 'TagsLogoImage',
    UserPrimaryImage = 'UserPrimaryImage'
}
/**
    * @export
    * @enum {string}
    */
export enum EmbyReportsApiModelReportHeaderDisplayTypeEnum {
    None = 'None',
    Screen = 'Screen',
    Export = 'Export',
    ScreenExport = 'ScreenExport'
}

