/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ImageByNameInfo
 */
export interface ImageByNameInfo {
    /**
     * 
     * @type {string}
     * @memberof ImageByNameInfo
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof ImageByNameInfo
     */
    theme?: any;
    /**
     * 
     * @type {string}
     * @memberof ImageByNameInfo
     */
    context?: any;
    /**
     * 
     * @type {number}
     * @memberof ImageByNameInfo
     */
    fileLength?: any;
    /**
     * 
     * @type {string}
     * @memberof ImageByNameInfo
     */
    format?: any;
}
