/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ItemCounts
 */
export interface ItemCounts {
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    movieCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    seriesCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    episodeCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    gameCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    artistCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    programCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    gameSystemCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    trailerCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    songCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    albumCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    musicVideoCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    boxSetCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    bookCount?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemCounts
     */
    itemCount?: any;
}
