/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LibraryAddVirtualFolder
 */
export interface LibraryAddVirtualFolder {
    /**
     * 
     * @type {string}
     * @memberof LibraryAddVirtualFolder
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof LibraryAddVirtualFolder
     */
    collectionType?: any;
    /**
     * 
     * @type {boolean}
     * @memberof LibraryAddVirtualFolder
     */
    refreshLibrary?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof LibraryAddVirtualFolder
     */
    paths?: any;
    /**
     * 
     * @type {ConfigurationLibraryOptions}
     * @memberof LibraryAddVirtualFolder
     */
    libraryOptions?: any;
}
