/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LibraryMediaFolder
 */
export interface LibraryMediaFolder {
    /**
     * 
     * @type {string}
     * @memberof LibraryMediaFolder
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof LibraryMediaFolder
     */
    id?: any;
    /**
     * 
     * @type {Array&lt;LibrarySubFolder&gt;}
     * @memberof LibraryMediaFolder
     */
    subFolders?: any;
}
