/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LiveTvTunerHostInfo
 */
export interface LiveTvTunerHostInfo {
    /**
     * 
     * @type {string}
     * @memberof LiveTvTunerHostInfo
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvTunerHostInfo
     */
    url?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvTunerHostInfo
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvTunerHostInfo
     */
    deviceId?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvTunerHostInfo
     */
    friendlyName?: any;
    /**
     * 
     * @type {boolean}
     * @memberof LiveTvTunerHostInfo
     */
    importFavoritesOnly?: any;
    /**
     * 
     * @type {boolean}
     * @memberof LiveTvTunerHostInfo
     */
    allowHWTranscoding?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvTunerHostInfo
     */
    source?: any;
    /**
     * 
     * @type {number}
     * @memberof LiveTvTunerHostInfo
     */
    tunerCount?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvTunerHostInfo
     */
    userAgent?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvTunerHostInfo
     */
    referrer?: any;
}
