/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LiveTvListingsProviderInfo
 */
export interface LiveTvListingsProviderInfo {
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    setupUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    username?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    password?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    listingsId?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    zipCode?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    country?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    path?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof LiveTvListingsProviderInfo
     */
    enabledTuners?: any;
    /**
     * 
     * @type {boolean}
     * @memberof LiveTvListingsProviderInfo
     */
    enableAllTuners?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof LiveTvListingsProviderInfo
     */
    newsCategories?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof LiveTvListingsProviderInfo
     */
    sportsCategories?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof LiveTvListingsProviderInfo
     */
    kidsCategories?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof LiveTvListingsProviderInfo
     */
    movieCategories?: any;
    /**
     * 
     * @type {Array&lt;NameValuePair&gt;}
     * @memberof LiveTvListingsProviderInfo
     */
    channelMappings?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    moviePrefix?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    preferredLanguage?: any;
    /**
     * 
     * @type {string}
     * @memberof LiveTvListingsProviderInfo
     */
    userAgent?: any;
}
