/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LogFile
 */
export interface LogFile {
    /**
     * 
     * @type {Date}
     * @memberof LogFile
     */
    dateCreated?: any;
    /**
     * 
     * @type {Date}
     * @memberof LogFile
     */
    dateModified?: any;
    /**
     * 
     * @type {number}
     * @memberof LogFile
     */
    size?: any;
    /**
     * 
     * @type {string}
     * @memberof LogFile
     */
    name?: any;
}
