/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MediaEncodingCodecsCommonTypesLevelInformation
 */
export interface MediaEncodingCodecsCommonTypesLevelInformation {
    /**
     * 
     * @type {string}
     * @memberof MediaEncodingCodecsCommonTypesLevelInformation
     */
    shortName?: any;
    /**
     * 
     * @type {string}
     * @memberof MediaEncodingCodecsCommonTypesLevelInformation
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof MediaEncodingCodecsCommonTypesLevelInformation
     */
    ordinal?: any | null;
    /**
     * 
     * @type {MediaEncodingCodecsCommonTypesBitRate}
     * @memberof MediaEncodingCodecsCommonTypesLevelInformation
     */
    maxBitRate?: any;
    /**
     * 
     * @type {string}
     * @memberof MediaEncodingCodecsCommonTypesLevelInformation
     */
    maxBitRateDisplay?: any;
    /**
     * 
     * @type {string}
     * @memberof MediaEncodingCodecsCommonTypesLevelInformation
     */
    id?: any;
    /**
     * 
     * @type {Array&lt;MediaEncodingCodecsCommonTypesResolutionWithRate&gt;}
     * @memberof MediaEncodingCodecsCommonTypesLevelInformation
     */
    resolutionRates?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof MediaEncodingCodecsCommonTypesLevelInformation
     */
    resolutionRateStrings?: any;
    /**
     * 
     * @type {string}
     * @memberof MediaEncodingCodecsCommonTypesLevelInformation
     */
    resolutionRatesDisplay?: any;
}
