/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MetadataEditorInfo
 */
export interface MetadataEditorInfo {
    /**
     * 
     * @type {Array&lt;ParentalRating&gt;}
     * @memberof MetadataEditorInfo
     */
    parentalRatingOptions?: any;
    /**
     * 
     * @type {Array&lt;GlobalizationCountryInfo&gt;}
     * @memberof MetadataEditorInfo
     */
    countries?: any;
    /**
     * 
     * @type {Array&lt;GlobalizationCultureDto&gt;}
     * @memberof MetadataEditorInfo
     */
    cultures?: any;
    /**
     * 
     * @type {Array&lt;ExternalIdInfo&gt;}
     * @memberof MetadataEditorInfo
     */
    externalIdInfos?: any;
}
