/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlaystateRequest
 */
export interface PlaystateRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaystateRequest
     */
    command?: PlaystateRequestCommandEnum;
    /**
     * 
     * @type {number}
     * @memberof PlaystateRequest
     */
    seekPositionTicks?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PlaystateRequest
     */
    controllingUserId?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum PlaystateRequestCommandEnum {
    Stop = 'Stop',
    Pause = 'Pause',
    Unpause = 'Unpause',
    NextTrack = 'NextTrack',
    PreviousTrack = 'PreviousTrack',
    Seek = 'Seek',
    Rewind = 'Rewind',
    FastForward = 'FastForward',
    PlayPause = 'PlayPause'
}

