/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProvidersMusicVideoInfo
 */
export interface ProvidersMusicVideoInfo {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ProvidersMusicVideoInfo
     */
    artists?: any;
    /**
     * 
     * @type {string}
     * @memberof ProvidersMusicVideoInfo
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof ProvidersMusicVideoInfo
     */
    metadataLanguage?: any;
    /**
     * 
     * @type {string}
     * @memberof ProvidersMusicVideoInfo
     */
    metadataCountryCode?: any;
    /**
     * 
     * @type {Array&lt;ModelObject&gt;}
     * @memberof ProvidersMusicVideoInfo
     */
    providerIds?: any;
    /**
     * 
     * @type {number}
     * @memberof ProvidersMusicVideoInfo
     */
    year?: any | null;
    /**
     * 
     * @type {number}
     * @memberof ProvidersMusicVideoInfo
     */
    indexNumber?: any | null;
    /**
     * 
     * @type {number}
     * @memberof ProvidersMusicVideoInfo
     */
    parentIndexNumber?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof ProvidersMusicVideoInfo
     */
    premiereDate?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProvidersMusicVideoInfo
     */
    isAutomated?: any;
    /**
     * 
     * @type {boolean}
     * @memberof ProvidersMusicVideoInfo
     */
    enableAdultMetadata?: any;
}
