/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProvidersGameInfo
 */
export interface ProvidersGameInfo {
    /**
     * 
     * @type {string}
     * @memberof ProvidersGameInfo
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof ProvidersGameInfo
     */
    metadataLanguage?: any;
    /**
     * 
     * @type {string}
     * @memberof ProvidersGameInfo
     */
    metadataCountryCode?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof ProvidersGameInfo
     */
    providerIds?: any;
    /**
     * 
     * @type {number}
     * @memberof ProvidersGameInfo
     */
    year?: any | null;
    /**
     * 
     * @type {number}
     * @memberof ProvidersGameInfo
     */
    indexNumber?: any | null;
    /**
     * 
     * @type {number}
     * @memberof ProvidersGameInfo
     */
    parentIndexNumber?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof ProvidersGameInfo
     */
    premiereDate?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProvidersGameInfo
     */
    isAutomated?: any;
}
