/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RecommendationDto
 */
export interface RecommendationDto {
    /**
     * 
     * @type {Array&lt;BaseItemDto&gt;}
     * @memberof RecommendationDto
     */
    items?: any;
    /**
     * 
     * @type {string}
     * @memberof RecommendationDto
     */
    recommendationType?: RecommendationDtoRecommendationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof RecommendationDto
     */
    baselineItemName?: any;
    /**
     * 
     * @type {number}
     * @memberof RecommendationDto
     */
    categoryId?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum RecommendationDtoRecommendationTypeEnum {
    SimilarToRecentlyPlayed = 'SimilarToRecentlyPlayed',
    SimilarToLikedItem = 'SimilarToLikedItem',
    HasDirectorFromRecentlyPlayed = 'HasDirectorFromRecentlyPlayed',
    HasActorFromRecentlyPlayed = 'HasActorFromRecentlyPlayed',
    HasLikedDirector = 'HasLikedDirector',
    HasLikedActor = 'HasLikedActor'
}

