/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RemoteImageInfo
 */
export interface RemoteImageInfo {
    /**
     * 
     * @type {string}
     * @memberof RemoteImageInfo
     */
    providerName?: any;
    /**
     * 
     * @type {string}
     * @memberof RemoteImageInfo
     */
    url?: any;
    /**
     * 
     * @type {string}
     * @memberof RemoteImageInfo
     */
    thumbnailUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof RemoteImageInfo
     */
    height?: any | null;
    /**
     * 
     * @type {number}
     * @memberof RemoteImageInfo
     */
    width?: any | null;
    /**
     * 
     * @type {number}
     * @memberof RemoteImageInfo
     */
    communityRating?: any | null;
    /**
     * 
     * @type {number}
     * @memberof RemoteImageInfo
     */
    voteCount?: any | null;
    /**
     * 
     * @type {string}
     * @memberof RemoteImageInfo
     */
    language?: any;
    /**
     * 
     * @type {string}
     * @memberof RemoteImageInfo
     */
    displayLanguage?: any;
    /**
     * 
     * @type {string}
     * @memberof RemoteImageInfo
     */
    type?: RemoteImageInfoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof RemoteImageInfo
     */
    ratingType?: RemoteImageInfoRatingTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum RemoteImageInfoTypeEnum {
    Primary = 'Primary',
    Art = 'Art',
    Backdrop = 'Backdrop',
    Banner = 'Banner',
    Logo = 'Logo',
    Thumb = 'Thumb',
    Disc = 'Disc',
    Box = 'Box',
    Screenshot = 'Screenshot',
    Menu = 'Menu',
    Chapter = 'Chapter',
    BoxRear = 'BoxRear',
    Thumbnail = 'Thumbnail',
    LogoLight = 'LogoLight',
    LogoLightColor = 'LogoLightColor'
}
/**
    * @export
    * @enum {string}
    */
export enum RemoteImageInfoRatingTypeEnum {
    Score = 'Score',
    Likes = 'Likes'
}

