/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SessionSessionInfo
 */
export interface SessionSessionInfo {
    /**
     * 
     * @type {PlayerStateInfo}
     * @memberof SessionSessionInfo
     */
    playState?: any;
    /**
     * 
     * @type {Array&lt;SessionUserInfo&gt;}
     * @memberof SessionSessionInfo
     */
    additionalUsers?: any;
    /**
     * 
     * @type {ClientCapabilities}
     * @memberof SessionSessionInfo
     */
    capabilities?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    remoteEndPoint?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SessionSessionInfo
     */
    playableMediaTypes?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    playlistItemId?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    serverId?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    userId?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    userName?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    userPrimaryImageTag?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    client?: any;
    /**
     * 
     * @type {Date}
     * @memberof SessionSessionInfo
     */
    lastActivityDate?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    deviceName?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    deviceType?: any;
    /**
     * 
     * @type {BaseItemDto}
     * @memberof SessionSessionInfo
     */
    nowPlayingItem?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    deviceId?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    applicationVersion?: any;
    /**
     * 
     * @type {string}
     * @memberof SessionSessionInfo
     */
    appIconUrl?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof SessionSessionInfo
     */
    supportedCommands?: any;
    /**
     * 
     * @type {TranscodingInfo}
     * @memberof SessionSessionInfo
     */
    transcodingInfo?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SessionSessionInfo
     */
    supportsRemoteControl?: any;
}
