/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SyncModelItemFileInfo
 */
export interface SyncModelItemFileInfo {
    /**
     * 
     * @type {string}
     * @memberof SyncModelItemFileInfo
     */
    type?: SyncModelItemFileInfoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SyncModelItemFileInfo
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncModelItemFileInfo
     */
    path?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncModelItemFileInfo
     */
    imageType?: SyncModelItemFileInfoImageTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof SyncModelItemFileInfo
     */
    index?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum SyncModelItemFileInfoTypeEnum {
    Media = 'Media',
    Image = 'Image',
    Subtitles = 'Subtitles'
}
/**
    * @export
    * @enum {string}
    */
export enum SyncModelItemFileInfoImageTypeEnum {
    Primary = 'Primary',
    Art = 'Art',
    Backdrop = 'Backdrop',
    Banner = 'Banner',
    Logo = 'Logo',
    Thumb = 'Thumb',
    Disc = 'Disc',
    Box = 'Box',
    Screenshot = 'Screenshot',
    Menu = 'Menu',
    Chapter = 'Chapter',
    BoxRear = 'BoxRear',
    Thumbnail = 'Thumbnail',
    LogoLight = 'LogoLight',
    LogoLightColor = 'LogoLightColor'
}

