/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SyncModelSyncProfileOption
 */
export interface SyncModelSyncProfileOption {
    /**
     * 
     * @type {string}
     * @memberof SyncModelSyncProfileOption
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncModelSyncProfileOption
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncModelSyncProfileOption
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SyncModelSyncProfileOption
     */
    isDefault?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SyncModelSyncProfileOption
     */
    enableQualityOptions?: any;
}
