/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SyncModelSyncedItemProgress
 */
export interface SyncModelSyncedItemProgress {
    /**
     * 
     * @type {number}
     * @memberof SyncModelSyncedItemProgress
     */
    progress?: any | null;
    /**
     * 
     * @type {string}
     * @memberof SyncModelSyncedItemProgress
     */
    status?: SyncModelSyncedItemProgressStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SyncModelSyncedItemProgressStatusEnum {
    Queued = 'Queued',
    Converting = 'Converting',
    ReadyToTransfer = 'ReadyToTransfer',
    Transferring = 'Transferring',
    Synced = 'Synced',
    Failed = 'Failed'
}

