/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SyncSyncJob
 */
export interface SyncSyncJob {
    /**
     * 
     * @type {number}
     * @memberof SyncSyncJob
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    targetId?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    targetName?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    quality?: any;
    /**
     * 
     * @type {number}
     * @memberof SyncSyncJob
     */
    bitrate?: any | null;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    container?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    videoCodec?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    audioCodec?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    profile?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    category?: SyncSyncJobCategoryEnum;
    /**
     * 
     * @type {number}
     * @memberof SyncSyncJob
     */
    parentId?: any;
    /**
     * 
     * @type {number}
     * @memberof SyncSyncJob
     */
    progress?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    status?: SyncSyncJobStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof SyncSyncJob
     */
    userId?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SyncSyncJob
     */
    unwatchedOnly?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SyncSyncJob
     */
    syncNewContent?: any;
    /**
     * 
     * @type {number}
     * @memberof SyncSyncJob
     */
    itemLimit?: any | null;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof SyncSyncJob
     */
    requestedItemIds?: any;
    /**
     * 
     * @type {Date}
     * @memberof SyncSyncJob
     */
    dateCreated?: any;
    /**
     * 
     * @type {Date}
     * @memberof SyncSyncJob
     */
    dateLastModified?: any;
    /**
     * 
     * @type {number}
     * @memberof SyncSyncJob
     */
    itemCount?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    parentName?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    primaryImageItemId?: any;
    /**
     * 
     * @type {string}
     * @memberof SyncSyncJob
     */
    primaryImageTag?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum SyncSyncJobCategoryEnum {
    Latest = 'Latest',
    NextUp = 'NextUp',
    Resume = 'Resume'
}
/**
    * @export
    * @enum {string}
    */
export enum SyncSyncJobStatusEnum {
    Queued = 'Queued',
    Converting = 'Converting',
    ReadyToTransfer = 'ReadyToTransfer',
    Transferring = 'Transferring',
    Completed = 'Completed',
    CompletedWithError = 'CompletedWithError',
    Failed = 'Failed'
}

