/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateUserEasyPassword
 */
export interface UpdateUserEasyPassword {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserEasyPassword
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserEasyPassword
     */
    newPw?: any;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserEasyPassword
     */
    resetPassword?: any;
}
