/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserItemDataDto
 */
export interface UserItemDataDto {
    /**
     * 
     * @type {number}
     * @memberof UserItemDataDto
     */
    rating?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UserItemDataDto
     */
    playedPercentage?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UserItemDataDto
     */
    unplayedItemCount?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UserItemDataDto
     */
    playbackPositionTicks?: any;
    /**
     * 
     * @type {number}
     * @memberof UserItemDataDto
     */
    playCount?: any;
    /**
     * 
     * @type {boolean}
     * @memberof UserItemDataDto
     */
    isFavorite?: any;
    /**
     * 
     * @type {Date}
     * @memberof UserItemDataDto
     */
    lastPlayedDate?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserItemDataDto
     */
    played?: any;
    /**
     * 
     * @type {string}
     * @memberof UserItemDataDto
     */
    key?: any;
    /**
     * 
     * @type {string}
     * @memberof UserItemDataDto
     */
    itemId?: any;
}
