/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VirtualFolderInfo
 */
export interface VirtualFolderInfo {
    /**
     * 
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    name?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof VirtualFolderInfo
     */
    locations?: any;
    /**
     * 
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    collectionType?: any;
    /**
     * 
     * @type {ConfigurationLibraryOptions}
     * @memberof VirtualFolderInfo
     */
    libraryOptions?: any;
    /**
     * 
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    itemId?: any;
    /**
     * 
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    primaryImageItemId?: any;
    /**
     * 
     * @type {number}
     * @memberof VirtualFolderInfo
     */
    refreshProgress?: any | null;
    /**
     * 
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    refreshStatus?: any;
}
