/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.6.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { EmbyWebGenericEditEditObjectContainer } from '../models';
/**
 * FfmpegOptionsServiceApi - axios parameter creator
 * @export
 */
export const FfmpegOptionsServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Requires authentication as user
         * @summary Gets the ffmpeg options
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEncodingFfmpegoptions: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/Encoding/FfmpegOptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apikeyauth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("api_key")
                    : await configuration.apiKey;
                localVarQueryParameter["api_key"] = localVarApiKeyValue;
            }

            // authentication embyauth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Requires authentication as administrator
         * @summary Updates the ffmpeg options
         * @param {Object} body Binary stream
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEncodingFfmpegoptions: async (body: Object, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postEncodingFfmpegoptions.');
            }
            const localVarPath = `/Encoding/FfmpegOptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apikeyauth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("api_key")
                    : await configuration.apiKey;
                localVarQueryParameter["api_key"] = localVarApiKeyValue;
            }

            // authentication embyauth required

            localVarHeaderParameter['Content-Type'] = 'application/octet-stream';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FfmpegOptionsServiceApi - functional programming interface
 * @export
 */
export const FfmpegOptionsServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Requires authentication as user
         * @summary Gets the ffmpeg options
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEncodingFfmpegoptions(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmbyWebGenericEditEditObjectContainer>> {
            const localVarAxiosArgs = await FfmpegOptionsServiceApiAxiosParamCreator(configuration).getEncodingFfmpegoptions(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Requires authentication as administrator
         * @summary Updates the ffmpeg options
         * @param {Object} body Binary stream
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postEncodingFfmpegoptions(body: Object, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await FfmpegOptionsServiceApiAxiosParamCreator(configuration).postEncodingFfmpegoptions(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * FfmpegOptionsServiceApi - factory interface
 * @export
 */
export const FfmpegOptionsServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Requires authentication as user
         * @summary Gets the ffmpeg options
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEncodingFfmpegoptions(options?: any): AxiosPromise<EmbyWebGenericEditEditObjectContainer> {
            return FfmpegOptionsServiceApiFp(configuration).getEncodingFfmpegoptions(options).then((request) => request(axios, basePath));
        },
        /**
         * Requires authentication as administrator
         * @summary Updates the ffmpeg options
         * @param {Object} body Binary stream
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEncodingFfmpegoptions(body: Object, options?: any): AxiosPromise<void> {
            return FfmpegOptionsServiceApiFp(configuration).postEncodingFfmpegoptions(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FfmpegOptionsServiceApi - object-oriented interface
 * @export
 * @class FfmpegOptionsServiceApi
 * @extends {BaseAPI}
 */
export class FfmpegOptionsServiceApi extends BaseAPI {
    /**
     * Requires authentication as user
     * @summary Gets the ffmpeg options
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FfmpegOptionsServiceApi
     */
    public getEncodingFfmpegoptions(options?: any) {
        return FfmpegOptionsServiceApiFp(this.configuration).getEncodingFfmpegoptions(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Requires authentication as administrator
     * @summary Updates the ffmpeg options
     * @param {Object} body Binary stream
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FfmpegOptionsServiceApi
     */
    public postEncodingFfmpegoptions(body: Object, options?: any) {
        return FfmpegOptionsServiceApiFp(this.configuration).postEncodingFfmpegoptions(body, options).then((request) => request(this.axios, this.basePath));
    }
}
